### ISSUE TITLE
the issue of toy datasets download

### ISSUE THREAD

**Issue by undade** [CTPLab/AutoCI#1]
I'm really sorry to bother you. I'm having a little problem with the toy datasets link you provided on github, I click on the link and the page says "Sorry, the file you requested does not exist".

**Comment by musikisomorphie** [comment]
Hi, thank you for raising this issue. 
I have updated download links. Let me know if it works now.

**Comment by undade** [comment]
> Hi, thank you for raising this issue.嗨，感谢您提出这个问题。 I have updated download links. Let me know if it works now.我已经更新了下载链接。让我知道它现在是否有效。

Thank you very much for your reply, the updated links work well!
